export enum EventStatus {
    PENDING = "PENDING",
    APPROVED_MANAGER = "APPROVED_MANAGER",
    APPROVED_CLIENT = "APPROVED_CLIENT",
    CANCELLED_MANAGER = "CANCELLED_MANAGER",
    CANCELLED_CLIENT = "CANCELLED_CLIENT",
    COMPLETED = "COMPLETED"
  }